from tkinter import*
from tkinter.messagebox import *
import sqlite3 as s
con=s.connect("login1.db")
con.execute("create table if not exists log1(username text, password text,mailid text,phonenumber number,gender text)")
obj=Tk()
obj.title("login")
obj.geometry("500x500")
obj.configure(bg="green")
var=StringVar()
var1=StringVar()
var2=StringVar()
var3=StringVar()
var4=StringVar()
var5=StringVar()
v=IntVar()
def login():
    x=var.get()
    y=var1.get()
    if(x=="admin" and y=="admin"):
        toplevel1=Toplevel()
        toplevel1.geometry("500x500")
        l1=Label(toplevel1,text="welcome").place(x=50,y=120)
        toplevel1.mainloop()
    c=con.cursor()
    c.execute("SELECT * FROM 'log1'WHERE 'username'=? AND 'password'=?",(var.get(),var1.get()))
    c.execute("SELECT username,password from log1" )
    r=c.fetchall()
    for i in r:
        if(i[0]==var.get() and i[1]==var1.get()):
            toplevel2=Toplevel()
            toplevel2.geometry("500x500")
            toplevel2.configure(bg="gold")
            l3=Label(toplevel2,text="WELCOME"+"   "+var.get(),bg="gold",font=("times new roman",18)).place(x=150,y=100)
            toplevel2.mainloop()
            break
    else:
      showinfo("Title", "invalid user")
    con.commit()
    con.close()
    var.set('')
    var1.set('')
def sql():
    con=s.connect("login1.db")
    con.execute("insert into log1 values(?,?,?,?,?)",(var2.get(),var3.get(),var4.get(),var5.get(),v.get()))
    con.commit()
    con.close()                     
def new():
    toplevel=Toplevel()
    toplevel.title("new user")
    toplevel.geometry("600x600")
    toplevel.configure(bg="green3")
    l2=Label(toplevel,text="N E W  U S E R",font=("times new roman",18),bg="green3",fg="black").place(x=120,y=50)
    l=Label(toplevel,text="User name").place(x=70,y=95)
    e=Entry(toplevel,textvariable=var2).place(x=175,y=95)
    l1=Label(toplevel,text="Password").place(x=70,y=125)
    e1=Entry(toplevel,textvariable=var3).place(x=175,y=125)
    l2=Label(toplevel,text="Mail id").place(x=70,y=150)
    e2=Entry(toplevel,textvariable=var4).place(x=175,y=150)
    l3=Label(toplevel,text="Phone number").place(x=70,y=175)
    e3=Entry(toplevel,textvariable=var5).place(x=175,y=175)
    l4=Label(toplevel,text="Gender").place(x=70,y=200)
    rb=Radiobutton(toplevel,text="Male",bg="green3",font=(14),variable=v,value=0 ).place(x=175,y=200)
    rb=Radiobutton(toplevel,text="Female",bg="green3",font=(14),variable=v,value=1).place(x=175,y=230)
    cb=Checkbutton(toplevel,text="I accept the terms and conditions",bg="green3",font=(14)).place(x=70,y=265)
    l5=Button(toplevel,text="REGISTER",command=sql).place(x=150,y=300)
    toplevel.mainloop()
l2=Label(obj,text="L O G I N   P A G E",font="1",bg="green",fg="white").place(x=170,y=150)
l=Label(obj,text="user name").place(x=120,y=200)
e=Entry(obj,textvariable=var).place(x=185,y=200)
l1=Label(obj,text="password").place(x=120,y=230)
e1=Entry(obj,textvariable=var1,show="*").place(x=185,y=230)
b1=Button(obj,text="submit",command=login).place(x=185,y=270)
b2=Button(obj,text="new user",command=new).place(x=245,y=270)
obj.mainloop()

